[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# Auto-publish settings
[context.production]
  publish = "."

[context.deploy-preview]
  publish = "."

# Redirects
[[redirects]]
  from = "/insights/*"
  to = "/focal/:splat"
  status = 301

# Portal Redirects
[[redirects]]
  from = "/checkalt-portal/*"
  to = "/client-portals/checkalt-portal/:splat"
  status = 301

[[redirects]]
  from = "/hc3-portal/*"
  to = "/client-portals/hc3-portal/:splat"
  status = 301

[[redirects]]
  from = "/horicon-bank-portal/*"
  to = "/client-portals/horicon-bank-portal/:splat"
  status = 301

[[redirects]]
  from = "/do-portal/*"
  to = "/client-portals/do-portal/:splat"
  status = 301
